"""PAINT 16x16 toolbar tool icons.

The icons are baked data in ``mmbasic/src/paint_tool_icons.h``, generated by
``assets/paint/gen_tool_icons.py``. These tests keep the committed header in
sync with the generator and assert the shape contract ``draw_tool_icon`` relies
on: 13 glyphs, each 16x16, each with visible ink, and tone values limited to
transparent / ink / cut.
"""
import importlib.util
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART_H = os.path.join(REPO, "mmbasic", "src", "paint_tool_icons.h")
GEN = os.path.join(REPO, "assets", "paint", "gen_tool_icons.py")

TRANSPARENT, INK, CUT = 0, 1, 2


def _load_gen():
    spec = importlib.util.spec_from_file_location("gen_tool_icons", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generator_matches_committed_output():
    mod = _load_gen()
    with open(ART_H, "r", encoding="utf-8") as fh:
        committed = fh.read()
    assert mod.emit_h(mod.build()) == committed, "regenerate paint_tool_icons.h"


def test_all_tools_have_a_16x16_glyph():
    mod = _load_gen()
    arts = mod.build()
    assert len(arts) == len(mod.TOOLS) == 16
    for name, art in zip(mod.TOOLS, arts):
        assert len(art) == 16, name
        assert all(len(row) == 16 for row in art), name


def test_glyphs_have_ink_and_valid_tones():
    mod = _load_gen()
    for name, art in zip(mod.TOOLS, mod.build()):
        tones = {v for row in art for v in row}
        assert tones <= {TRANSPARENT, INK, CUT}, (name, tones)
        ink = sum(1 for row in art for v in row if v == INK)
        assert ink > 0, name
