"""PAINT 32x32 tool cursor art (#632).

The art is baked data in ``mmbasic/src/paint_cursor_art.c``, generated by
``assets/paint/gen_cursor_art.py``. These tests compile the data with a host
toolchain and assert the sanity contract the cursor runtime relies on:
every sprite is 32x32, its hotspot is inside the sprite **and names a
non-transparent pixel** (#690), and idle differs from active for the
selection-bearing tools. A second test keeps the committed output in sync with
the generator.
"""
import importlib.util
import os
import shutil
import subprocess

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "mmbasic", "src")
ART_C = os.path.join(SRC, "paint_cursor_art.c")
ART_H = os.path.join(SRC, "paint_cursor_art.h")
GEN = os.path.join(REPO, "assets", "paint", "gen_cursor_art.py")

W = H = 32
TRANSPARENT = 255

TOOLS = [
    "arrow", "pencil", "line", "rectangle", "ellipse", "circle", "fill",
    "eraser", "pick", "grab", "magnify", "airbrush", "spray", "text",
    "select",
]

# Tools whose idle and active art must differ (button-held feedback).
SELECTION_TOOLS = set(TOOLS)

DRIVER = r"""
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "paint_cursor_art.h"

static unsigned fnv(const uint8_t *p, int n) {
    unsigned h = 2166136261u;
    for (int i = 0; i < n; i++) {
        h ^= p[i];
        h *= 16777619u;
    }
    return h;
}

static int opaque_count(const uint8_t *p, int n) {
    int c = 0;
    for (int i = 0; i < n; i++) {
        if (p[i] != PCA_CURSOR_TRANSPARENT) c++;
    }
    return c;
}

int main(void) {
    printf("COUNT %d\n", PCA_TOOL_COUNT);
    printf("DIM %d %d\n", PCA_CURSOR_W, PCA_CURSOR_H);
    for (int i = 0; i < PCA_TOOL_COUNT; i++) {
        const pca_sprite_t *s = &pca_sprites[i];
        printf("%s %u %u %d %d %d %d %d %d %d %d %d\n",
               s->name,
               fnv(s->idle, PCA_CURSOR_PIXELS),
               fnv(s->active, PCA_CURSOR_PIXELS),
               s->idle_hotspot_x, s->idle_hotspot_y,
               s->active_hotspot_x, s->active_hotspot_y,
               s->transparent,
               opaque_count(s->idle, PCA_CURSOR_PIXELS),
               opaque_count(s->active, PCA_CURSOR_PIXELS),
               s->idle[s->idle_hotspot_y * PCA_CURSOR_W + s->idle_hotspot_x],
               s->active[s->active_hotspot_y * PCA_CURSOR_W +
                        s->active_hotspot_x]);
    }
    return 0;
}
"""


@pytest.fixture(scope="module")
def sprites(tmp_path_factory):
    if shutil.which("cc") is None:
        pytest.skip("needs a host C toolchain (cc)")
    tmp = tmp_path_factory.mktemp("paint_cursor_art")
    driver = tmp / "driver.c"
    driver.write_text(DRIVER)
    exe = tmp / "driver"
    subprocess.run(
        [
            "cc", "-std=c11", "-O0", "-Wall", "-Wextra", "-Werror",
            "-I", SRC, "-o", str(exe), str(driver), ART_C,
        ],
        check=True,
        cwd=REPO,
    )
    out = subprocess.run([str(exe)], check=True, capture_output=True, text=True)
    parsed = {}
    count = None
    dim = None
    for line in out.stdout.splitlines():
        parts = line.split()
        if parts[0] == "COUNT":
            count = int(parts[1])
        elif parts[0] == "DIM":
            dim = (int(parts[1]), int(parts[2]))
        else:
            name = parts[0]
            parsed[name] = {
                "idle_hash": parts[1],
                "active_hash": parts[2],
                "idle_hot": (int(parts[3]), int(parts[4])),
                "active_hot": (int(parts[5]), int(parts[6])),
                "transparent": int(parts[7]),
                "idle_opaque": int(parts[8]),
                "active_opaque": int(parts[9]),
                "idle_hot_px": int(parts[10]),
                "active_hot_px": int(parts[11]),
            }
    return count, dim, parsed


def test_every_tool_has_idle_and_active_art(sprites):
    count, dim, parsed = sprites
    assert count == len(TOOLS)
    assert dim == (W, H)
    assert set(parsed) == set(TOOLS)


def test_hotspots_in_bounds(sprites):
    _, _, parsed = sprites
    for name, s in parsed.items():
        for hx, hy in (s["idle_hot"], s["active_hot"]):
            assert 0 <= hx < W, (name, hx)
            assert 0 <= hy < H, (name, hy)


def test_hotspot_names_an_opaque_pixel(sprites):
    """#690: a hotspot on a transparent pixel lands the pointer beside the art.

    The tip of a pointer (arrow, pencil) or the centre of a shape must be a
    pixel the runtime actually stamps, in both the idle and active art.
    """
    _, _, parsed = sprites
    for name, s in parsed.items():
        assert s["idle_hot_px"] != TRANSPARENT, (name, "idle", s["idle_hot"])
        assert s["active_hot_px"] != TRANSPARENT, (name, "active", s["active_hot"])


def test_sprites_have_opaque_pixels(sprites):
    _, _, parsed = sprites
    for name, s in parsed.items():
        assert s["transparent"] == TRANSPARENT, name
        assert s["idle_opaque"] > 0, name
        assert s["active_opaque"] > 0, name


def test_idle_and_active_differ_for_selection_tools(sprites):
    _, _, parsed = sprites
    for name in SELECTION_TOOLS:
        s = parsed[name]
        assert s["idle_hash"] != s["active_hash"], name


def test_generator_matches_committed_output():
    spec = importlib.util.spec_from_file_location("gen_cursor_art", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    with open(ART_H, "r", encoding="utf-8") as fh:
        committed_h = fh.read()
    with open(ART_C, "r", encoding="utf-8") as fh:
        committed_c = fh.read()

    arts = mod.build()
    assert mod.emit_h() == committed_h, "regenerate paint_cursor_art.h"
    assert mod.emit_c(arts) == committed_c, "regenerate paint_cursor_art.c"
