#!/usr/bin/env python3
"""Generate mmbasic/src/ramdisk_data.c from the versioned ``ramdisk/`` tree.

Every non-hidden file under ``ramdisk/`` is embedded as a byte array plus a
``{ path, data, length }`` table (sorted, so builds are reproducible). The
generated file is build output and is git-ignored.

Fails the build with a clear message if a path component would not fit in a
VFS node name or if the tree would exceed the VFS node budget (read from
``mmbasic/src/vfs.c``).
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_RAMDISK = REPO / "ramdisk"
DEFAULT_OUT = REPO / "mmbasic" / "src" / "ramdisk_data.c"
VFS_SRC = REPO / "mmbasic" / "src" / "vfs.c"

NAME_MAX = 79  # vfs_node.name[80]


def read_vfs_max(path: Path = VFS_SRC) -> int:
    src = path.read_text()
    m = re.search(r"#define\s+VFS_MAX\s+(\d+)", src)
    if not m:
        raise SystemExit("gen_ramdisk: cannot find #define VFS_MAX in vfs.c")
    return int(m.group(1))


def collect(root: Path, excludes: list[str]):
    files: list[str] = []
    dirs: set[str] = set()
    if not root.is_dir():
        return files, dirs
    for path in root.rglob("*"):
        rel = path.relative_to(root)
        parts = rel.parts
        if any(p.startswith(".") for p in parts):
            continue
        if path.is_dir():
            continue
        if not path.is_file():
            continue
        relstr = "/".join(parts)
        if any(relstr == e or relstr.startswith(e + "/") for e in excludes):
            continue
        files.append(relstr)
        for i in range(1, len(parts)):
            dirs.add("/".join(parts[:i]))
    files.sort()
    return files, dirs


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def read_bytes(path: Path) -> bytes:
    with open(path, "rb") as fh:
        return fh.read()


def render(root: Path, files, dirs, mode: str) -> str:
    out: list[str] = []
    out.append("/* Generated by scripts/gen_ramdisk.py - do not edit.")
    out.append(f" * mode: {mode}")
    out.append(" */")
    out.append('#include "mmb_priv.h"')
    out.append("")
    table: list[str] = []
    if not files:
        out.append("const int mmb_ramdisk_count = 0;")
        out.append("const mmb_ramdisk_entry mmb_ramdisk_table[] = { { 0, 0, 0 } };")
        out.append("")
        return "\n".join(out)
    for i, rel in enumerate(files):
        data = read_bytes(root / rel)
        name = f"rd_{i}"
        out.append(f"static const unsigned char {name}[] = {{")
        if data:
            for j in range(0, len(data), 12):
                chunk = ", ".join(f"0x{b:02X}" for b in data[j : j + 12])
                out.append(f"\t{chunk},")
        else:
            out.append("\t0,")
        out.append("};")
        table.append(f'\t{{ "{c_escape(rel)}", {name}, {len(data)}u }},')
    out.append("")
    out.append("const int mmb_ramdisk_count = %d;" % len(files))
    out.append("const mmb_ramdisk_entry mmb_ramdisk_table[] = {")
    out.extend(table)
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=str(DEFAULT_RAMDISK))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--exclude", default="", help="comma-separated rel paths to drop")
    ap.add_argument("--vfs-src", default=str(VFS_SRC))
    args = ap.parse_args()

    root = Path(args.root)
    out_path = Path(args.out)
    excludes = [e.strip().strip("/") for e in args.exclude.split(",") if e.strip()]

    files, dirs = collect(root, excludes)

    for rel in files:
        for part in rel.split("/"):
            if len(part) > NAME_MAX:
                sys.stderr.write(
                    f"gen_ramdisk: path component too long ({len(part)} > {NAME_MAX}): "
                    f"{rel}\n"
                )
                return 1

    max_nodes = read_vfs_max(Path(args.vfs_src))
    used = len(files) + len(dirs)
    if used > max_nodes:
        sys.stderr.write(
            f"gen_ramdisk: ramdisk needs {used} VFS nodes but VFS_MAX is {max_nodes}; "
            f"raise VFS_MAX in vfs.c or remove files\n"
        )
        return 1

    mode = "exclude=" + (",".join(excludes) if excludes else "-")
    text = render(root, files, dirs, mode)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if out_path.read_text() == text:
            return 0
    except FileNotFoundError:
        pass
    out_path.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
